version: "3.4"
services:
  # vpn:
  #   container_name: vpn
  #   image: dperson/openvpn-client:arm64v8-latest
  #   cap_add:
  #     - net_admin # required to modify network interfaces
  #   restart: unless-stopped
  #   volumes:
  #     - /dev/net:/dev/net:z # tun device
  #     - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
  #   security_opt:
  #     - label:disable
  #   ports:
  #     - 8112:8112 # port for deluge web UI to be reachable from local network
  #   command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:arm64v8-latest
    restart: unless-stopped
    network_mode: host # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
      - /mnt/hdd/:/mnt/hdd/ # Hard Disk

  jackett:
    container_name: jackett
    image: linuxserver/jackett:arm64v8-latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
      - /mnt/hdd/:/mnt/hdd/ # Hard Disk

  # nzbget:
  #   container_name: nzbget
  #   image: linuxserver/nzbget:arm64v8-latest
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #   volumes:
  #     - ${ROOT}/downloads:/downloads # download folder
  #     - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:arm64v8-latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
      - /mnt/hdd/:/mnt/hdd/ # Hard Disk

  radarr:
    container_name: radarr
    image: linuxserver/radarr:arm64v8-latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
      - /mnt/hdd/:/mnt/hdd/ # Hard Disk

  plex-server:
    container_name: plex-server
    image: linuxserver/plex:arm64v8-latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VERSION=docker # Set whether to update plex or not - see Application Setup section.
    network_mode: host
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
      - /mnt/hdd/:/mnt/hdd/ # Hard Disk
  # bazarr:
  #   container_name: bazarr
  #   image: linuxserver/bazarr
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - UMASK_SET=022 #optional
  #   volumes:
  #     - ${ROOT}/config/bazarr:/config # config files
  #     - ${ROOT}/complete/movies:/movies # movies folder
  #     - ${ROOT}/complete/tv:/tv # tv shows folder
  #     - /mnt/hdd/:/mnt/hdd/ # Hard Disk
  #   ports:
  #     - 6767:6767
